name: format

on:
  push:
    branches:
      - "dev"
      - "main"
    paths:
      - 'lua/**'

jobs:
  stylua-check:
    name: "Formatting check with Stylua"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua
